POST http://localhost:3003/api/blogs
Content-Type: "application/json"
{
    "title": "The best programming practice",
    "author": "Alex Tomas",
    "url": "https://bestprogrammingtips.com",
    "likes": 233
}