DELETE http://localhost:3003/api/blogs/62bafaeae4c022f5beebf3d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpY2hhYnJhdmEiLCJpZCI6IjYyYmFmYWJiZTRjMDIyZjViZWViZjNjYSIsImlhdCI6MTY1NjQyMTE2MCwiZXhwIjoxNjU3MDI1OTYwfQ.QDbgu7LMX6c2pe9Fi4r_NASJkCTtd4JpGfaCRkSHU4M