POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Daniela es muy lista lo esta entendiendo todo"
    
}

###

POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    
}
